export const mainapi=`http://127.0.0.1:8000/api/`;
export const Registerr ="register";
export const Loginn ="login";
export const Loogout ="logout";
export const users ="users";
export const CAT ="categories";
export const cat ="category";
export const PRO ="products";
export const pro ="product";
export const auth="auth/google/callback"
export const Tokenuser ="user";